# Generated by Django 4.2.6 on 2023-12-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pending_fees',
            field=models.BigIntegerField(default=0),
        ),
    ]
